name: Build Pipeline 
on: [push, pull_request]

jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          # LTS releases & latest release
          java: [8, 11, 17, 18]

      steps:
        - name: Check out code 
          uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Setup java ${{ matrix.java }}
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: ${{ matrix.java }}

        - name: Build using Gradle
          run: ./gradlew build
